version: "3"
services:
  vlm-redis:
    container_name: vlm-redis
    image: redis
    ports:
      - "6379:6379"

  vlm-jobs:
    container_name: vlm-jobs
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4567:4567"
    volumes:
      - "./index.json:/opt/arena/index.json"
    depends_on:
      - vlm-redis
