version: '3'
services:
  redis:
    container_name: vlm-redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - vlm-jobs-network
  
  jobs:
    container_name: vlm-jobs
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4567:4567'
    volumes:
      - './index.json:/opt/arena/index.json'
    depends_on:
      - redis
    networks:
      - vlm-jobs-network

networks:
  vlm-jobs-network:
    name: vlm
